apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: headlamp-system
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4466
      # nodePort: 30005
  selector:
    app: headlamp

