apiVersion: v1
kind: Service
metadata:
  name: sftpgo
spec:
  type: NodePort
  selector:
    app: sftpgo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30804
    - name: sftp
      port: 2022
      targetPort: 2022
      protocol: TCP
