apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  PAPERLESS_DBHOST: "postgres"
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg:3000"
  PAPERLESS_TIKA_ENDPOINT: "http://tika:9998"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_TIME_ZONE: "UTC"
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_PORT: "8000"
  PAPERLESS_URL: "https://drive.manosriram.com"
  PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://drive.manosriram.com"
