apiVersion: v1
kind: Service
metadata:
  name: pocketid-service
spec:
  type: NodePort
  selector:
    app: pocketid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1411
      nodePort: 30205
