apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      containers:
      - name: pocketid
        image: ghcr.io/pocket-id/pocket-id:latest
        ports:
        - containerPort: 1411
        env:
        - name: APP_URL
          value: "https://id.manosriram.com"
        - name: TRUST_PROXY
          value: "true"
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: pocketid-secret
              key: ENCRYPTION_KEY
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pocketid-data
